name: geolocator_web
description: Official web implementation of the geolocator plugin.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_web
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 2.1.6

flutter:
  plugin:
    platforms:
      web:
        pluginClass: GeolocatorPlugin
        fileName: geolocator_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  geolocator_platform_interface:
    path: ../geolocator_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mockito: ^5.0.0-nullsafety.7

environment:
  sdk: '>=2.13.1 <3.0.0'
  flutter: ">=2.2.1"
