name: geolocator_apple
description: Geolocation Apple plugin for Flutter. This plugin provides the Apple implementation for the geolocator.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_apple
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 2.2.1

environment:
  sdk: ">=2.13.1 <3.0.0"
  flutter: ">=2.2.1"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: GeolocatorPlugin
        dartPluginClass: GeolocatorApple
      macos:
        pluginClass: GeolocatorPlugin
        dartPluginClass: GeolocatorApple

dependencies:
  flutter:
    sdk: flutter

  geolocator_platform_interface:
    path: ../geolocator_platform_interface
  
dev_dependencies:
  async: ^2.8.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.0.0-nullsafety.7
  plugin_platform_interface: ^1.0.1
