name: geolocator_windows
description: Geolocation Windows plugin for Flutter. This plugin provides the Windows implementation for the geolocator.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_windows
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 0.1.1

environment:
  sdk: ">=2.13.1 <3.0.0"
  flutter: ">=2.2.1"

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: GeolocatorWindows

dependencies:
  flutter:
    sdk: flutter

  geolocator_platform_interface:
    path: ../geolocator_platform_interface
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mockito: ^5.0.0-nullsafety.7
  plugin_platform_interface: ^1.0.1
